#!/bin/bash
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
export PATH="$JAVA_HOME/bin:$PATH"
export LD_LIBRARY_PATH=/usr/lib/jvm/java-21-openjdk-amd64/lib/server:$LD_LIBRARY_PATH

echo "JAVA_HOME set to $JAVA_HOME"
echo "PATH set to $PATH"
echo "LD_LIBRARY_PATH set to $LD_LIBRARY_PATH"

# Run the original entrypoint script (important!)
exec "$@"
